export const NEW_EXPERIMENT_PIPELINES_STEP = 1;
export const NEW_EXPERIMENT_DATASETS_STEP = 2;
export const NEW_EXPERIMENT_RUNTIME_GROUPING_STEP = 3;
export const NEW_EXPERIMENT_REVIEW_STEP = 4;
export const NEW_EXPERIMENT_LAUNCH_STEP = 5;

export const NEW_EXPERIMENT_FIRST_STEP = NEW_EXPERIMENT_PIPELINES_STEP;
export const NEW_EXPERIMENT_MAX_STEP = NEW_EXPERIMENT_LAUNCH_STEP;

export type NewExperimentWizardStep =
  | typeof NEW_EXPERIMENT_PIPELINES_STEP
  | typeof NEW_EXPERIMENT_DATASETS_STEP
  | typeof NEW_EXPERIMENT_RUNTIME_GROUPING_STEP
  | typeof NEW_EXPERIMENT_REVIEW_STEP
  | typeof NEW_EXPERIMENT_LAUNCH_STEP;

export interface NewExperimentStepProgressItem {
  id: NewExperimentWizardStep;
  label: string;
}

export interface NewExperimentStepProgressViewItem extends NewExperimentStepProgressItem {
  isActive: boolean;
  isCompleted: boolean;
  isLast: boolean;
}

export const NEW_EXPERIMENT_STEP_PROGRESS_ITEMS: NewExperimentStepProgressItem[] = [
  { id: NEW_EXPERIMENT_PIPELINES_STEP, label: "Select Pipelines" },
  { id: NEW_EXPERIMENT_DATASETS_STEP, label: "Select Datasets" },
  { id: NEW_EXPERIMENT_RUNTIME_GROUPING_STEP, label: "Runtime Grouping" },
  { id: NEW_EXPERIMENT_REVIEW_STEP, label: "Review" },
  { id: NEW_EXPERIMENT_LAUNCH_STEP, label: "Launch" },
];

export interface NewExperimentStepReadinessInput {
  currentStep: number;
  selectedPipelineCount: number;
  selectedDatasetCount: number;
  hasGroupingBlockingError: boolean;
}

export function buildNewExperimentStepProgress(
  currentStep: NewExperimentWizardStep,
): NewExperimentStepProgressViewItem[] {
  return NEW_EXPERIMENT_STEP_PROGRESS_ITEMS.map((step, index) => ({
    ...step,
    isActive: step.id === currentStep,
    isCompleted: step.id < currentStep,
    isLast: index === NEW_EXPERIMENT_STEP_PROGRESS_ITEMS.length - 1,
  }));
}

export function canProceedNewExperimentStep({
  currentStep,
  selectedPipelineCount,
  selectedDatasetCount,
  hasGroupingBlockingError,
}: NewExperimentStepReadinessInput): boolean {
  if (currentStep === NEW_EXPERIMENT_PIPELINES_STEP) return selectedPipelineCount > 0;
  if (currentStep === NEW_EXPERIMENT_DATASETS_STEP) return selectedDatasetCount > 0;
  if (currentStep === NEW_EXPERIMENT_RUNTIME_GROUPING_STEP) return !hasGroupingBlockingError;
  return true;
}

export function getPreviousNewExperimentStep(step: NewExperimentWizardStep): NewExperimentWizardStep {
  return clampNewExperimentStep(step - 1);
}

export function getNextNewExperimentStep(step: NewExperimentWizardStep): NewExperimentWizardStep {
  return clampNewExperimentStep(step + 1);
}

export function shouldShowNewExperimentWizardActions(step: NewExperimentWizardStep): boolean {
  return step < NEW_EXPERIMENT_LAUNCH_STEP;
}

export function shouldApplyAutoGeneratedExperimentName({
  currentStep,
  currentName,
  autoGeneratedName,
}: {
  currentStep: NewExperimentWizardStep;
  currentName: string;
  autoGeneratedName: string;
}): boolean {
  return currentStep === NEW_EXPERIMENT_REVIEW_STEP && currentName === "" && autoGeneratedName !== "";
}

function clampNewExperimentStep(step: number): NewExperimentWizardStep {
  if (step <= NEW_EXPERIMENT_FIRST_STEP) return NEW_EXPERIMENT_FIRST_STEP;
  if (step >= NEW_EXPERIMENT_MAX_STEP) return NEW_EXPERIMENT_MAX_STEP;
  return step as NewExperimentWizardStep;
}
