import type { PipelineInfo } from "@/api/pipelines";
import type {
  ExperimentExecutionAdapter,
  ExperimentExecutionAdapterResolution,
} from "@/lib/experimentExecutionAdapter";
import type { NewExperimentNativeBackendAvailability } from "@/lib/experimentExecutionEnvironment";
import type {
  DatasetRuntimeGroupingState,
  SelectedPipelinesRuntimeGrouping,
} from "@/lib/runtimeSplitGrouping";
import { buildCampaignPlanPreview } from "@/lib/campaignPlanPreview";
import { buildCampaignSinglePairSplitSpecs } from "@/lib/campaignSinglePairSplitPreview";
import type {
  CampaignPlanPreview,
  CampaignSinglePairSplitSpecResult,
} from "@/lib/campaignPlanPreviewTypes";
import type {
  CampaignExecutionBackend,
  CampaignSpec,
} from "@/lib/campaignSpecTypes";
import { resolveExperimentExecutionAdapter } from "@/lib/experimentExecutionAdapter";
import {
  buildExperimentCampaignSpec,
  getSelectedGroupingPayload,
} from "@/lib/experimentCampaignAdapter";
import type { ExperimentDatasetOption } from "@/lib/experimentDatasetOptions";
import { buildAutoExperimentName } from "@/lib/experimentNaming";
import {
  getSelectedPipelineConfigs,
  type CurrentEditedPipeline,
  type ExperimentPipelineOption,
  type SelectedPipelineConfig,
} from "@/lib/experimentPipelineSelection";
import {
  analyzeSelectedPipelinesRuntimeGrouping,
  evaluateDatasetRuntimeGrouping,
} from "@/lib/runtimeSplitGrouping";

export interface NewExperimentPlanFlowInput {
  datasets: ExperimentDatasetOption[];
  rawPipelines: PipelineInfo[];
  allPipelineOptions: ExperimentPipelineOption[];
  currentEditedPipeline: CurrentEditedPipeline | null;
  selectedDatasetIds: string[];
  selectedPipelineIds: string[];
  splitGroupByByDataset: Record<string, string | null>;
  customExperimentName?: string;
  experimentDescription?: string;
  executionBackend?: CampaignExecutionBackend;
  availableExecutionAdapters?: readonly ExperimentExecutionAdapter[];
  nativeBackendAvailability?: readonly NewExperimentNativeBackendAvailability[];
}

export interface NewExperimentPlanFlowState {
  autoGeneratedName: string;
  campaignPreview: CampaignPlanPreview;
  campaignSpec: CampaignSpec;
  datasetById: Map<string, ExperimentDatasetOption>;
  datasetGroupingStates: Record<string, DatasetRuntimeGroupingState>;
  executionAdapterResolution: ExperimentExecutionAdapterResolution;
  experimentName: string;
  groupingSelection: SelectedPipelinesRuntimeGrouping;
  hasGroupingBlockingError: boolean;
  selectedGroupingPayload: Record<string, string | null>;
  selectedPipelineConfigs: SelectedPipelineConfig[];
  singlePairSplitSpecResult: CampaignSinglePairSplitSpecResult;
}

export function buildNewExperimentPlanFlowState({
  datasets,
  rawPipelines,
  allPipelineOptions,
  currentEditedPipeline,
  selectedDatasetIds,
  selectedPipelineIds,
  splitGroupByByDataset,
  customExperimentName = "",
  experimentDescription = "",
  executionBackend = "local-python",
  availableExecutionAdapters,
  nativeBackendAvailability,
}: NewExperimentPlanFlowInput): NewExperimentPlanFlowState {
  const datasetById = new Map(datasets.map((dataset) => [dataset.id, dataset]));
  const selectedPipelineConfigs = getSelectedPipelineConfigs(
    rawPipelines,
    selectedPipelineIds,
    currentEditedPipeline,
  );
  const groupingSelection = analyzeSelectedPipelinesRuntimeGrouping(selectedPipelineConfigs);
  const datasetGroupingStates = Object.fromEntries(
    selectedDatasetIds
      .map((datasetId) => {
        const dataset = datasetById.get(datasetId)?.raw;
        return dataset
          ? [datasetId, evaluateDatasetRuntimeGrouping(dataset, groupingSelection, splitGroupByByDataset[datasetId] ?? null)] as const
          : null;
      })
      .filter((entry): entry is readonly [string, DatasetRuntimeGroupingState] => Boolean(entry)),
  );
  const hasGroupingBlockingError =
    groupingSelection.hasPersistedGroupConflict ||
    selectedDatasetIds.some((datasetId) => datasetGroupingStates[datasetId]?.hasBlockingError);
  const selectedGroupingPayload = getSelectedGroupingPayload(selectedDatasetIds, splitGroupByByDataset);
  const autoGeneratedName = buildAutoExperimentName({
    selectedDatasetIds,
    selectedPipelineIds,
    datasetsById: datasetById,
    pipelines: allPipelineOptions,
    currentEditedPipeline,
  });
  const experimentName = customExperimentName.trim() || autoGeneratedName;
  const campaignSpec = buildExperimentCampaignSpec({
    name: experimentName,
    description: experimentDescription,
    selectedDatasetIds,
    datasetById,
    selectedPipelineConfigs,
    selectedGroupingPayload,
    executionBackend,
  });
  const campaignPreview = buildCampaignPlanPreview(campaignSpec, {
    availableExecutionAdapters,
    nativeBackendAvailability,
  });
  const singlePairSplitSpecResult = buildCampaignSinglePairSplitSpecs(campaignSpec);
  const executionAdapterResolution = resolveExperimentExecutionAdapter(campaignSpec.executionBackend, {
    availableAdapters: availableExecutionAdapters,
  });

  return {
    autoGeneratedName,
    campaignPreview,
    campaignSpec,
    datasetById,
    datasetGroupingStates,
    executionAdapterResolution,
    experimentName,
    groupingSelection,
    hasGroupingBlockingError,
    selectedGroupingPayload,
    selectedPipelineConfigs,
    singlePairSplitSpecResult,
  };
}
