/**
 * @vitest-environment jsdom
 */

import { act } from "react";
import { createRoot } from "react-dom/client";
import { describe, expect, it } from "vitest";

import type { PipelineInfo } from "@/api/pipelines";
import type { Dataset } from "@/types/datasets";
import { toExperimentDatasetOption } from "@/lib/experimentDatasetOptions";
import {
  CLUSTER_EXPERIMENT_EXECUTION_ADAPTER,
  LEGACY_LOCAL_EXPERIMENT_EXECUTION_ADAPTER,
} from "@/lib/experimentExecutionAdapter";
import { DEFAULT_NEW_EXPERIMENT_EXECUTION_ENVIRONMENT } from "@/lib/experimentExecutionEnvironment";
import {
  buildAllPipelineOptions,
  CURRENT_EDITED_PIPELINE_ID,
  toExperimentPipelineOption,
  type CurrentEditedPipeline,
} from "@/lib/experimentPipelineSelection";

import { useNewExperimentPlanFlow, type UseNewExperimentPlanFlowInput } from "./useNewExperimentPlanFlow";

(globalThis as typeof globalThis & { IS_REACT_ACT_ENVIRONMENT?: boolean })
  .IS_REACT_ACT_ENVIRONMENT = true;

async function renderHook<T>(hook: () => T) {
  const container = document.createElement("div");
  document.body.appendChild(container);
  const root = createRoot(container);
  const result: { current: T | undefined } = { current: undefined };

  function TestComponent() {
    result.current = hook();
    return null;
  }

  await act(async () => {
    root.render(<TestComponent />);
  });

  return {
    result,
    unmount: async () => {
      await act(async () => {
        root.unmount();
      });
      container.remove();
    },
  };
}

function dataset(overrides: Partial<Dataset> = {}): Dataset {
  return {
    id: "d1",
    name: "Corn",
    path: "/data/corn",
    linked_at: "2026-01-01T00:00:00",
    num_samples: 42,
    num_features: 128,
    default_target: "protein",
    metadata_columns: ["batch", "year"],
    config: {
      delimiter: ",",
      decimal_separator: ".",
      has_header: true,
      repetition: "sample_id",
    },
    ...overrides,
  };
}

function pipeline(overrides: Partial<PipelineInfo> = {}): PipelineInfo {
  return {
    id: "p1",
    name: "PLS Pipeline",
    category: "custom",
    steps: [
      { id: "split", name: "KFold", type: "splitting", params: { n_splits: 5 } },
      { id: "model", name: "PLS", type: "model", params: {} },
    ],
    created_at: "2026-01-01T00:00:00",
    updated_at: "2026-01-01T00:00:00",
    ...overrides,
  };
}

function planFlowInput(
  overrides: Partial<UseNewExperimentPlanFlowInput> = {},
): UseNewExperimentPlanFlowInput {
  const rawPipelines = overrides.rawPipelines ?? [pipeline()];
  const datasets = overrides.datasets ?? [toExperimentDatasetOption(dataset())];

  return {
    datasets,
    rawPipelines,
    allPipelineOptions: rawPipelines.map(toExperimentPipelineOption),
    currentEditedPipeline: null,
    selectedDatasetIds: ["d1"],
    selectedPipelineIds: ["p1"],
    splitGroupByByDataset: {},
    customExperimentName: "",
    experimentDescription: "",
    ...overrides,
  };
}

describe("useNewExperimentPlanFlow", () => {
  it("derives the selected cartesian campaign plan from selected datasets and pipelines", async () => {
    const mounted = await renderHook(() => useNewExperimentPlanFlow(planFlowInput({
      splitGroupByByDataset: { d1: "batch" },
    })));

    expect(mounted.result.current!.autoGeneratedName).toBe("Corn x PLS Pipeline");
    expect(mounted.result.current!.experimentName).toBe("Corn x PLS Pipeline");
    expect(mounted.result.current!.selectedGroupingPayload).toEqual({ d1: "batch" });
    expect(mounted.result.current!.selectedPipelineConfigs).toEqual([
      {
        id: "p1",
        name: "PLS Pipeline",
        steps: pipeline().steps,
      },
    ]);
    expect(mounted.result.current!.campaignSpec).toMatchObject({
      name: "Corn x PLS Pipeline",
      datasets: [{ id: "d1", name: "Corn", splitGroupBy: "batch" }],
      pipelines: [{ id: "p1", name: "PLS Pipeline", source: "saved", stepCount: 2 }],
      runMatrix: [{ id: "d1::p1", splitGroupBy: "batch" }],
    });
    expect(mounted.result.current!.campaignPreview.summary.runCount).toBe(1);
    expect(mounted.result.current!.executionAdapterResolution.statusLabel).toBe("Native adapter");

    await mounted.unmount();
  });

  it("propagates native backend availability into campaign previews", async () => {
    const mounted = await renderHook(() => useNewExperimentPlanFlow(planFlowInput({
      executionBackend: "cluster",
      availableExecutionAdapters: DEFAULT_NEW_EXPERIMENT_EXECUTION_ENVIRONMENT.availableExecutionAdapters,
      nativeBackendAvailability: DEFAULT_NEW_EXPERIMENT_EXECUTION_ENVIRONMENT.nativeBackendAvailability,
    })));

    expect(mounted.result.current!.campaignPreview.executionAdapter).toEqual({
      id: "legacy-local",
      label: "Legacy local run API",
      statusLabel: "Legacy fallback",
      message: "Cluster execution is typed but no native submitter is configured.",
    });

    await mounted.unmount();
  });

  it("aligns campaign previews and launch adapter resolution for injected native backends", async () => {
    const mounted = await renderHook(() => useNewExperimentPlanFlow(planFlowInput({
      executionBackend: "cluster",
      availableExecutionAdapters: [
        LEGACY_LOCAL_EXPERIMENT_EXECUTION_ADAPTER,
        CLUSTER_EXPERIMENT_EXECUTION_ADAPTER,
      ],
    })));

    expect(mounted.result.current!.campaignSpec.executionBackend).toBe("cluster");
    expect(mounted.result.current!.campaignPreview.executionBackendLabel).toBe("Cluster");
    expect(mounted.result.current!.campaignPreview.executionAdapter).toEqual({
      id: "cluster",
      label: "Cluster execution adapter",
      statusLabel: "Native adapter",
      message: "Cluster execution adapter is selected for this campaign backend.",
    });
    expect(mounted.result.current!.campaignPreview.capabilityChecks).toContainEqual({
      id: "execution-backend-capabilities",
      status: "not_evaluated",
      statusLabel: "Not evaluated",
      title: "Execution backend capabilities",
      message: "Cluster execution adapter is selected for this backend; backend-specific method and compute-option checks are not evaluated yet.",
    });
    expect(mounted.result.current!.executionAdapterResolution).toMatchObject({
      adapter: CLUSTER_EXPERIMENT_EXECUTION_ADAPTER,
      requestedBackend: "cluster",
      isNativeForBackend: true,
      statusLabel: "Native adapter",
      message: "Cluster execution adapter is selected for this campaign backend.",
    });

    await mounted.unmount();
  });

  it("exposes strict single-pair campaign specs for the selected run matrix", async () => {
    const mounted = await renderHook(() => useNewExperimentPlanFlow(planFlowInput({
      datasets: [
        toExperimentDatasetOption(dataset({ id: "d1", name: "Corn" })),
        toExperimentDatasetOption(dataset({ id: "d2", name: "Wheat" })),
      ],
      rawPipelines: [
        pipeline({ id: "p1", name: "PLS Pipeline" }),
        pipeline({ id: "p2", name: "SVM Pipeline" }),
      ],
      allPipelineOptions: [
        toExperimentPipelineOption(pipeline({ id: "p1", name: "PLS Pipeline" })),
        toExperimentPipelineOption(pipeline({ id: "p2", name: "SVM Pipeline" })),
      ],
      selectedDatasetIds: ["d1", "d2"],
      selectedPipelineIds: ["p1", "p2"],
      splitGroupByByDataset: { d1: "batch", d2: null },
      customExperimentName: "Manual Matrix",
      executionBackend: "cluster",
      availableExecutionAdapters: [
        LEGACY_LOCAL_EXPERIMENT_EXECUTION_ADAPTER,
        CLUSTER_EXPERIMENT_EXECUTION_ADAPTER,
      ],
    })));

    expect(mounted.result.current!.singlePairSplitSpecResult.skippedRunIds).toEqual([]);
    expect(mounted.result.current!.singlePairSplitSpecResult.splitSpecs).toHaveLength(4);
    expect(mounted.result.current!.singlePairSplitSpecResult.splitSpecs[0]).toMatchObject({
      id: "single-pair:d1::p1",
      sourceRunId: "d1::p1",
      sourceDatasetId: "d1",
      sourcePipelineId: "p1",
      campaign: {
        name: "Manual Matrix / Corn -> PLS Pipeline",
        mode: "paired_by_index",
        executionBackend: "cluster",
        datasets: [{ id: "d1", name: "Corn", splitGroupBy: "batch" }],
        pipelines: [{ id: "p1", name: "PLS Pipeline", source: "saved" }],
        runMatrix: [
          {
            id: "d1::p1",
            datasetId: "d1",
            pipelineId: "p1",
            datasetIndex: 0,
            pipelineIndex: 0,
            splitGroupBy: "batch",
          },
        ],
      },
    });
    expect(mounted.result.current!.singlePairSplitSpecResult.splitSpecs[3].campaign).toMatchObject({
      name: "Manual Matrix / Wheat -> SVM Pipeline",
      datasets: [{ id: "d2", name: "Wheat", splitGroupBy: null }],
      pipelines: [{ id: "p2", name: "SVM Pipeline", source: "saved" }],
      runMatrix: [{ id: "d2::p2", datasetIndex: 0, pipelineIndex: 0 }],
    });

    await mounted.unmount();
  });

  it("uses custom experiment names without changing the generated fallback", async () => {
    const mounted = await renderHook(() => useNewExperimentPlanFlow(planFlowInput({
      customExperimentName: "  Custom Campaign  ",
      experimentDescription: "Preview run",
    })));

    expect(mounted.result.current!.autoGeneratedName).toBe("Corn x PLS Pipeline");
    expect(mounted.result.current!.experimentName).toBe("Custom Campaign");
    expect(mounted.result.current!.campaignSpec).toMatchObject({
      name: "Custom Campaign",
      description: "Preview run",
    });

    await mounted.unmount();
  });

  it("includes the current edited pipeline in configs and campaign previews", async () => {
    const currentEditedPipeline: CurrentEditedPipeline = {
      name: "Draft Pipeline",
      isDirty: true,
      steps: [{ id: "draft-step", name: "Draft Step", type: "model" }],
    };
    const savedOptions = [toExperimentPipelineOption(pipeline())];
    const mounted = await renderHook(() => useNewExperimentPlanFlow(planFlowInput({
      allPipelineOptions: buildAllPipelineOptions(currentEditedPipeline, savedOptions),
      currentEditedPipeline,
      selectedPipelineIds: [CURRENT_EDITED_PIPELINE_ID, "p1"],
    })));

    expect(mounted.result.current!.autoGeneratedName).toBe("Corn x Draf_PLS ");
    expect(mounted.result.current!.selectedPipelineConfigs.map((entry) => entry.id)).toEqual([
      CURRENT_EDITED_PIPELINE_ID,
      "p1",
    ]);
    expect(mounted.result.current!.campaignSpec.pipelines).toMatchObject([
      { id: CURRENT_EDITED_PIPELINE_ID, source: "inline", stepCount: 1 },
      { id: "p1", source: "saved", stepCount: 2 },
    ]);
    expect(mounted.result.current!.campaignPreview.summary.runCount).toBe(2);

    await mounted.unmount();
  });

  it("flags blocking runtime grouping when a required splitter has no effective group", async () => {
    const mounted = await renderHook(() => useNewExperimentPlanFlow(planFlowInput({
      datasets: [
        toExperimentDatasetOption(dataset({
          metadata_columns: ["batch"],
          config: {
            delimiter: ",",
            decimal_separator: ".",
            has_header: true,
          },
        })),
      ],
      rawPipelines: [
        pipeline({
          steps: [{ id: "split", name: "GroupKFold", type: "splitting", params: { n_splits: 5 } }],
        }),
      ],
      allPipelineOptions: [
        toExperimentPipelineOption(pipeline({
          steps: [{ id: "split", name: "GroupKFold", type: "splitting", params: { n_splits: 5 } }],
        })),
      ],
      splitGroupByByDataset: { d1: null },
    })));

    expect(mounted.result.current!.groupingSelection.hasRequiredSplitters).toBe(true);
    expect(mounted.result.current!.datasetGroupingStates.d1.hasBlockingError).toBe(true);
    expect(mounted.result.current!.hasGroupingBlockingError).toBe(true);

    await mounted.unmount();
  });
});
