import { useCallback, useEffect, useState } from "react";
import { useNavigate, useSearchParams } from "react-router-dom";
import { NewExperimentShell } from "@/components/experiments/NewExperimentShell";
import {
  useNewExperimentFilteredInputs,
  useNewExperimentInputData,
} from "@/hooks/useNewExperimentInputData";
import { useNewExperimentExecutionEnvironment } from "@/hooks/useNewExperimentExecutionEnvironment";
import { useNewExperimentLaunchFlow } from "@/hooks/useNewExperimentLaunchFlow";
import { useNewExperimentPlanFlow } from "@/hooks/useNewExperimentPlanFlow";
import { useNewExperimentSelectionFlow } from "@/hooks/useNewExperimentSelectionFlow";
import {
  canProceedNewExperimentStep,
  getNextNewExperimentStep,
  getPreviousNewExperimentStep,
  NEW_EXPERIMENT_FIRST_STEP,
  NEW_EXPERIMENT_RUNTIME_GROUPING_STEP,
  shouldApplyAutoGeneratedExperimentName,
  type NewExperimentWizardStep,
} from "@/lib/experimentWizardFlow";

export default function NewExperiment() {
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const [currentStep, setCurrentStep] = useState<NewExperimentWizardStep>(NEW_EXPERIMENT_FIRST_STEP);
  const [customExperimentName, setCustomExperimentName] = useState("");
  const [experimentDescription, setExperimentDescription] = useState("");

  const inputData = useNewExperimentInputData();
  const executionEnvironment = useNewExperimentExecutionEnvironment();
  const redirectToEditor = useCallback(() => {
    navigate("/editor", { replace: true });
  }, [navigate]);
  const selectionFlow = useNewExperimentSelectionFlow({
    savedPipelineOptions: inputData.pipelines,
    rawPipelines: inputData.rawPipelines,
    searchParams,
    onEditorRedirect: redirectToEditor,
  });
  const filteredInputs = useNewExperimentFilteredInputs({
    datasets: inputData.datasets,
    allPipelineOptions: selectionFlow.allPipelineOptions,
    datasetSearch: selectionFlow.datasetSearch,
    pipelineFilter: selectionFlow.pipelineFilter,
    pipelineSearch: selectionFlow.pipelineSearch,
  });

  const planFlow = useNewExperimentPlanFlow({
    datasets: inputData.datasets,
    rawPipelines: inputData.rawPipelines,
    allPipelineOptions: selectionFlow.allPipelineOptions,
    currentEditedPipeline: selectionFlow.currentEditedPipeline,
    selectedDatasetIds: selectionFlow.selectedDatasetIds,
    selectedPipelineIds: selectionFlow.selectedPipelineIds,
    splitGroupByByDataset: selectionFlow.splitGroupByByDataset,
    customExperimentName,
    experimentDescription,
    availableExecutionAdapters: executionEnvironment.availableExecutionAdapters,
    nativeBackendAvailability: executionEnvironment.nativeBackendAvailability,
  });

  useEffect(() => {
    if (shouldApplyAutoGeneratedExperimentName({
      currentStep,
      currentName: customExperimentName,
      autoGeneratedName: planFlow.autoGeneratedName,
    })) {
      setCustomExperimentName(planFlow.autoGeneratedName);
    }
  }, [currentStep, customExperimentName, planFlow.autoGeneratedName]);

  const canProceedCurrentStep = canProceedNewExperimentStep({
    currentStep,
    selectedPipelineCount: selectionFlow.selectedPipelineIds.length,
    selectedDatasetCount: selectionFlow.selectedDatasetIds.length,
    hasGroupingBlockingError: planFlow.hasGroupingBlockingError,
  });

  const launchFlow = useNewExperimentLaunchFlow({
    experimentName: planFlow.experimentName,
    experimentDescription,
    selectedDatasetIds: selectionFlow.selectedDatasetIds,
    selectedPipelineConfigs: planFlow.selectedPipelineConfigs,
    selectedGroupingPayload: planFlow.selectedGroupingPayload,
    singlePairSplitSpecResult: planFlow.singlePairSplitSpecResult,
    hasGroupingBlockingError: planFlow.hasGroupingBlockingError,
    executionAdapter: planFlow.executionAdapterResolution.adapter,
    launchSubmitters: executionEnvironment.launchSubmitters,
    onGroupingBlockingError: () => setCurrentStep(NEW_EXPERIMENT_RUNTIME_GROUPING_STEP),
    onRunCreated: (runId) => navigate(`/runs/${runId}`),
  });

  return (
    <NewExperimentShell
      canProceed={canProceedCurrentStep}
      currentStep={currentStep}
      customExperimentName={customExperimentName}
      executionEnvironmentDiagnostics={executionEnvironment.diagnostics}
      experimentDescription={experimentDescription}
      filteredInputs={filteredInputs}
      inputData={inputData}
      launchFlow={launchFlow}
      planFlow={planFlow}
      selectionFlow={selectionFlow}
      onExperimentDescriptionChange={setExperimentDescription}
      onExperimentNameChange={setCustomExperimentName}
      onBack={() => setCurrentStep(getPreviousNewExperimentStep)}
      onNext={() => setCurrentStep(getNextNewExperimentStep)}
      onExit={() => navigate("/runs")}
    />
  );
}
