import { describe, expect, it } from "vitest";

import {
  buildNewExperimentStepProgress,
  canProceedNewExperimentStep,
  getNextNewExperimentStep,
  getPreviousNewExperimentStep,
  NEW_EXPERIMENT_DATASETS_STEP,
  NEW_EXPERIMENT_FIRST_STEP,
  NEW_EXPERIMENT_LAUNCH_STEP,
  NEW_EXPERIMENT_MAX_STEP,
  NEW_EXPERIMENT_PIPELINES_STEP,
  NEW_EXPERIMENT_REVIEW_STEP,
  NEW_EXPERIMENT_RUNTIME_GROUPING_STEP,
  shouldApplyAutoGeneratedExperimentName,
  shouldShowNewExperimentWizardActions,
} from "@/lib/experimentWizardFlow";

describe("experimentWizardFlow", () => {
  it("keeps New Experiment step bounds and transitions centralized", () => {
    expect(NEW_EXPERIMENT_FIRST_STEP).toBe(1);
    expect(NEW_EXPERIMENT_MAX_STEP).toBe(5);
    expect(getPreviousNewExperimentStep(NEW_EXPERIMENT_FIRST_STEP)).toBe(NEW_EXPERIMENT_FIRST_STEP);
    expect(getPreviousNewExperimentStep(NEW_EXPERIMENT_RUNTIME_GROUPING_STEP)).toBe(NEW_EXPERIMENT_DATASETS_STEP);
    expect(getNextNewExperimentStep(NEW_EXPERIMENT_REVIEW_STEP)).toBe(NEW_EXPERIMENT_LAUNCH_STEP);
    expect(getNextNewExperimentStep(NEW_EXPERIMENT_LAUNCH_STEP)).toBe(NEW_EXPERIMENT_LAUNCH_STEP);
  });

  it("hides wizard actions only on the launch step", () => {
    expect(shouldShowNewExperimentWizardActions(NEW_EXPERIMENT_REVIEW_STEP)).toBe(true);
    expect(shouldShowNewExperimentWizardActions(NEW_EXPERIMENT_LAUNCH_STEP)).toBe(false);
  });

  it("builds step progress items from the centralized wizard order", () => {
    expect(buildNewExperimentStepProgress(NEW_EXPERIMENT_RUNTIME_GROUPING_STEP)).toEqual([
      {
        id: NEW_EXPERIMENT_PIPELINES_STEP,
        label: "Select Pipelines",
        isActive: false,
        isCompleted: true,
        isLast: false,
      },
      {
        id: NEW_EXPERIMENT_DATASETS_STEP,
        label: "Select Datasets",
        isActive: false,
        isCompleted: true,
        isLast: false,
      },
      {
        id: NEW_EXPERIMENT_RUNTIME_GROUPING_STEP,
        label: "Runtime Grouping",
        isActive: true,
        isCompleted: false,
        isLast: false,
      },
      {
        id: NEW_EXPERIMENT_REVIEW_STEP,
        label: "Review",
        isActive: false,
        isCompleted: false,
        isLast: false,
      },
      {
        id: NEW_EXPERIMENT_LAUNCH_STEP,
        label: "Launch",
        isActive: false,
        isCompleted: false,
        isLast: true,
      },
    ]);
  });

  it("computes step readiness from explicit counts and flags", () => {
    expect(canProceedNewExperimentStep({
      currentStep: NEW_EXPERIMENT_PIPELINES_STEP,
      selectedPipelineCount: 0,
      selectedDatasetCount: 1,
      hasGroupingBlockingError: false,
    })).toBe(false);
    expect(canProceedNewExperimentStep({
      currentStep: NEW_EXPERIMENT_PIPELINES_STEP,
      selectedPipelineCount: 1,
      selectedDatasetCount: 0,
      hasGroupingBlockingError: false,
    })).toBe(true);
    expect(canProceedNewExperimentStep({
      currentStep: NEW_EXPERIMENT_DATASETS_STEP,
      selectedPipelineCount: 1,
      selectedDatasetCount: 0,
      hasGroupingBlockingError: false,
    })).toBe(false);
    expect(canProceedNewExperimentStep({
      currentStep: NEW_EXPERIMENT_RUNTIME_GROUPING_STEP,
      selectedPipelineCount: 1,
      selectedDatasetCount: 1,
      hasGroupingBlockingError: true,
    })).toBe(false);
    expect(canProceedNewExperimentStep({
      currentStep: NEW_EXPERIMENT_REVIEW_STEP,
      selectedPipelineCount: 0,
      selectedDatasetCount: 0,
      hasGroupingBlockingError: true,
    })).toBe(true);
  });

  it("applies auto-generated names only on the review step with an empty current name", () => {
    expect(shouldApplyAutoGeneratedExperimentName({
      currentStep: NEW_EXPERIMENT_REVIEW_STEP,
      currentName: "",
      autoGeneratedName: "Campaign",
    })).toBe(true);
    expect(shouldApplyAutoGeneratedExperimentName({
      currentStep: NEW_EXPERIMENT_REVIEW_STEP,
      currentName: "Manual",
      autoGeneratedName: "Campaign",
    })).toBe(false);
    expect(shouldApplyAutoGeneratedExperimentName({
      currentStep: NEW_EXPERIMENT_RUNTIME_GROUPING_STEP,
      currentName: "",
      autoGeneratedName: "Campaign",
    })).toBe(false);
    expect(shouldApplyAutoGeneratedExperimentName({
      currentStep: NEW_EXPERIMENT_REVIEW_STEP,
      currentName: "",
      autoGeneratedName: "",
    })).toBe(false);
  });
});
