import { describe, expect, it } from "vitest";

import type { PipelineInfo } from "@/api/pipelines";
import type { Dataset } from "@/types/datasets";
import {
  CLUSTER_EXPERIMENT_EXECUTION_ADAPTER,
  LEGACY_LOCAL_EXPERIMENT_EXECUTION_ADAPTER,
} from "@/lib/experimentExecutionAdapter";
import { toExperimentDatasetOption } from "@/lib/experimentDatasetOptions";
import {
  CURRENT_EDITED_PIPELINE_ID,
  toExperimentPipelineOption,
  type CurrentEditedPipeline,
  type ExperimentPipelineOption,
} from "@/lib/experimentPipelineSelection";
import {
  buildNewExperimentPlanFlowState,
  type NewExperimentPlanFlowInput,
} from "../newExperimentPlanFlow";

function dataset(overrides: Partial<Dataset> = {}): Dataset {
  return {
    id: "d1",
    name: "Corn",
    path: "/data/corn",
    linked_at: "2026-01-01T00:00:00",
    num_samples: 42,
    num_features: 128,
    default_target: "protein",
    metadata_columns: ["batch", "year"],
    config: {
      delimiter: ",",
      decimal_separator: ".",
      has_header: true,
      repetition: "sample_id",
    },
    ...overrides,
  };
}

function pipeline(overrides: Partial<PipelineInfo> = {}): PipelineInfo {
  return {
    id: "p1",
    name: "PLS Pipeline",
    category: "custom",
    steps: [
      { id: "split", name: "KFold", type: "splitting", params: { n_splits: 5 } },
      { id: "model", name: "PLS", type: "model", params: {} },
    ],
    created_at: "2026-01-01T00:00:00",
    updated_at: "2026-01-01T00:00:00",
    ...overrides,
  };
}

function pipelineOption(
  overrides: Partial<ExperimentPipelineOption> & Pick<ExperimentPipelineOption, "id" | "name">,
): ExperimentPipelineOption {
  return {
    preset: false,
    favorite: false,
    steps: "",
    nodeCount: 0,
    activeNodeCount: 0,
    disabledNodeCount: 0,
    branchCount: 0,
    generatorCount: 0,
    stepGeneratorCount: 0,
    parameterSweepCount: 0,
    finetuneNodeCount: 0,
    refitNodeCount: 0,
    maxDepth: 0,
    ...overrides,
  };
}

function planFlowInput(
  overrides: Partial<NewExperimentPlanFlowInput> = {},
): NewExperimentPlanFlowInput {
  const rawPipelines = overrides.rawPipelines ?? [pipeline()];
  const datasets = overrides.datasets ?? [toExperimentDatasetOption(dataset())];

  return {
    datasets,
    rawPipelines,
    allPipelineOptions: rawPipelines.map(toExperimentPipelineOption),
    currentEditedPipeline: null,
    selectedDatasetIds: ["d1"],
    selectedPipelineIds: ["p1"],
    splitGroupByByDataset: {},
    customExperimentName: "",
    experimentDescription: "",
    ...overrides,
  };
}

describe("buildNewExperimentPlanFlowState", () => {
  it("builds the campaign, preview, adapter resolution, and strict single-pair specs", () => {
    const state = buildNewExperimentPlanFlowState(planFlowInput({
      datasets: [
        toExperimentDatasetOption(dataset({ id: "d1", name: "Corn" })),
        toExperimentDatasetOption(dataset({ id: "d2", name: "Wheat" })),
      ],
      rawPipelines: [
        pipeline({ id: "p1", name: "PLS Pipeline" }),
        pipeline({ id: "p2", name: "SVM Pipeline" }),
      ],
      allPipelineOptions: [
        toExperimentPipelineOption(pipeline({ id: "p1", name: "PLS Pipeline" })),
        toExperimentPipelineOption(pipeline({ id: "p2", name: "SVM Pipeline" })),
      ],
      selectedDatasetIds: ["d1", "d2"],
      selectedPipelineIds: ["p1", "p2"],
      splitGroupByByDataset: { d1: "batch", d2: null },
      customExperimentName: "  Manual Matrix  ",
      executionBackend: "cluster",
      availableExecutionAdapters: [
        LEGACY_LOCAL_EXPERIMENT_EXECUTION_ADAPTER,
        CLUSTER_EXPERIMENT_EXECUTION_ADAPTER,
      ],
    }));

    expect(state.autoGeneratedName).toBe("Corn_Whea x PLS _SVM ");
    expect(state.experimentName).toBe("Manual Matrix");
    expect(state.selectedGroupingPayload).toEqual({ d1: "batch", d2: null });
    expect(state.campaignSpec).toMatchObject({
      name: "Manual Matrix",
      mode: "legacy_cartesian",
      executionBackend: "cluster",
      datasets: [
        { id: "d1", name: "Corn", splitGroupBy: "batch" },
        { id: "d2", name: "Wheat", splitGroupBy: null },
      ],
      pipelines: [
        { id: "p1", name: "PLS Pipeline", source: "saved" },
        { id: "p2", name: "SVM Pipeline", source: "saved" },
      ],
    });
    expect(state.campaignPreview.summary.runCount).toBe(4);
    expect(state.executionAdapterResolution).toMatchObject({
      adapter: CLUSTER_EXPERIMENT_EXECUTION_ADAPTER,
      requestedBackend: "cluster",
      isNativeForBackend: true,
    });
    expect(state.singlePairSplitSpecResult.splitSpecs).toHaveLength(4);
  });

  it("includes the current edited pipeline and keeps runtime grouping blockers pure", () => {
    const currentEditedPipeline: CurrentEditedPipeline = {
      name: "Draft Pipeline",
      isDirty: true,
      steps: [{ id: "draft-step", name: "GroupKFold", type: "splitting", params: { n_splits: 5 } }],
    };
    const state = buildNewExperimentPlanFlowState(planFlowInput({
      datasets: [
        toExperimentDatasetOption(dataset({
          metadata_columns: ["batch"],
          config: {
            delimiter: ",",
            decimal_separator: ".",
            has_header: true,
          },
        })),
      ],
      rawPipelines: [pipeline()],
      allPipelineOptions: [
        pipelineOption({
          id: CURRENT_EDITED_PIPELINE_ID,
          name: "Draft Pipeline",
          steps: "GroupKFold",
          nodeCount: 1,
          activeNodeCount: 1,
          isCurrentEdited: true,
        }),
        toExperimentPipelineOption(pipeline()),
      ],
      currentEditedPipeline,
      selectedPipelineIds: [CURRENT_EDITED_PIPELINE_ID, "p1"],
      splitGroupByByDataset: { d1: null },
    }));

    expect(state.selectedPipelineConfigs.map((entry) => entry.id)).toEqual([
      CURRENT_EDITED_PIPELINE_ID,
      "p1",
    ]);
    expect(state.campaignSpec.pipelines).toMatchObject([
      { id: CURRENT_EDITED_PIPELINE_ID, source: "inline", stepCount: 1 },
      { id: "p1", source: "saved", stepCount: 2 },
    ]);
    expect(state.groupingSelection.hasRequiredSplitters).toBe(true);
    expect(state.datasetGroupingStates.d1.hasBlockingError).toBe(true);
    expect(state.hasGroupingBlockingError).toBe(true);
  });
});
